export const HALTE_NAMES: string[] = [
  'Terminal Purabaya',
  'Dukuh Menanggal',
  'Siwalankerto 1',
  'Taman Pelangi',
  'RS Bhayangkara',
  'UBHARA',
  'Pusvetma',
  'Ketintang',
  'Terminal Joyoboyo',
  'Museum BI',
  'RS Darmo',
  'GOZCO',
  'Pandegiling A',
  'Urip Sumoharjo A',
  'Basra',
  'Kaliasin',
  'Embong Malang',
  'Blauran',
  'Pirngadi',
  'Pasar Turi',
  'Masjid Kemayoran',
  'Indrapura',
  'Ikan Kerapu A',
  'Tanjung Torawitan A',
  'Barunawati A',
  'Pelindo Place A',
  'Tanjung Perak',
  'Pelindo Place B',
  'Barunawati B',
  'Tanjung Torawitan B',
  'Ikan Kerapu B',
  'Rajawali',
  'Jembatan Merah',
  'Veteran',
  'Tugu Pahlawan',
  'Alun-alun Contong',
  'Siola',
  'Tunjungan',
  'Simpang Dukuh',
  'Gubernur Suryo',
  'Pangsud',
  'Sono Kembang',
  'Urip Sumoharjo B',
  'Pandegiling B',
  'Santa Maria',
  'Darmo',
  'Marmoyo',
  'Joyoboyo 2',
  'RSAL',
  'Margorejo',
  'Wonocolo',
  'UINSA',
  'Jemur Ngawinan',
  'Siwalankerto 2',
  'Kertomenanggal',
  'Terminal Purabaya',
];
